"""Init

Revision ID: 459d1085a14a
Revises: 
Create Date: 2023-12-21 22:53:01.967888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '459d1085a14a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contacts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=100), nullable=False),
                    sa.Column('last_name', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('phone', sa.String(length=13), nullable=False),
                    sa.Column('birthday', sa.String(length=15), nullable=False),
                    sa.Column('completed', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_Contacts_birthday'), 'Contacts', ['birthday'], unique=False)
    op.create_index(op.f('ix_Contacts_email'), 'Contacts', ['email'], unique=True)
    op.create_index(op.f('ix_Contacts_id'), 'Contacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Contacts_id'), table_name='Contacts')
    op.drop_index(op.f('ix_Contacts_email'), table_name='Contacts')
    op.drop_index(op.f('ix_Contacts_birthday'), table_name='Contacts')
    op.drop_table('Contacts')
    # ### end Alembic commands ###
