"""add users

Revision ID: f78ed2ca84a9
Revises: 459d1085a14a
Create Date: 2023-12-27 19:30:56.653614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78ed2ca84a9'
down_revision: Union[str, None] = '459d1085a14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('Contacts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('Contacts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('Contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_Contacts_birthday', table_name='Contacts')
    op.drop_index('ix_Contacts_email', table_name='Contacts')
    op.drop_index('ix_Contacts_id', table_name='Contacts')
    op.create_foreign_key(None, 'Contacts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Contacts', type_='foreignkey')
    op.create_index('ix_Contacts_id', 'Contacts', ['id'], unique=False)
    op.create_index('ix_Contacts_email', 'Contacts', ['email'], unique=True)
    op.create_index('ix_Contacts_birthday', 'Contacts', ['birthday'], unique=False)
    op.drop_column('Contacts', 'user_id')
    op.drop_column('Contacts', 'updated_at')
    op.drop_column('Contacts', 'created_at')
    op.drop_table('users')
    # ### end Alembic commands ###
